name: Build

on:
  push:
    branches: [master, fix-ffmpegPath-win]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - name: Build windows executable
        run: npx electron-builder build --win portable

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Production Build
          files: dist/*.exe
